name: cnn_2d
input_type: img # (e.g., features, text, img, signal, ...)
pretrained_path: null # (e.g., "src/models/xxx.pth")

#################
#   parameters  #
#################
epochs: 20
early: 20
learning_rate: 1e-2
l2_rate: 0
batch_size: 128
test_batch_size: 256

optimizer: RAdam
criterion: CrossEntropy # {MAE, MSE, BinaryCrossEntropy, CrossEntropy, ...}
use_weighted_loss: False

which_model: "valid_best" # {last, valid_best, test_best}
monitor: "f1" # {loss, acc, f1, auc, rmse, ...}

output_size: 10 # (# of classes for classification, 1 for regression)

#################
#   scheduler   #
#################
scheduler: "CosineLRScheduler" #timm
lr_min: 1e-6
warmup_t: 5

# scheduler: "CosineAnnealingLR"
# scheduler_cycle: 200
# lr_min: 1e-6

# scheduler: null


#################
#  augmentation #
#################
use_noise: True


###自動定義###
num_channels: # None
input_size: # None