name: mlp
input_type: features # (e.g., features, text, image)
pretrained_path: null # (e.g., "src/models/xxx.pth")

#################
#   parameters  #
#################
epochs: 10
early: 10
learning_rate: 1e-2
l2_rate: 0
batch_size: 32
test_batch_size: 256

optimizer: RAdam
criterion: MSE # {MAE, MSE, BinaryCrossEntropy, CrossEntropyLoss, ...}
use_weighted_loss: False

which_model: "test_best" # {last, valid_best, test_best}
monitor: "loss" # {loss, acc, f1, auc, rmse, ...}

output_size: 1 # (# of classes for classification, 1 for regression)

#################
#   scheduler   #
#################
scheduler: "CosineLRScheduler" #timm
lr_min: 1e-6
warmup_t: 5

# scheduler: "CosineAnnealingLR"
# scheduler_cycle: 200
# lr_min: 1e-6

# scheduler: null


#################
#  augmentation #
#################
use_noise: True


###自動定義###
num_channels: # None
input_size: # None